import "@/src/styles/tos.css";

export default function TermsOfServicePage() {
  return (
    <div className="my-10 px-4 sm:px-10 md:px-32">
      <TermsofService />
    </div>
  );
}

function TermsofService() {
  return (
    <>
      <h1>Terms of Service for Quarkle</h1>
      <p className="text-sm italic">Effective Date: December 15, 2023</p>
      <ol>
        <li>Introduction</li>
        <p>Welcome to Quarkle. By accessing or using Quarkle, you agree to be bound by these Terms of Service ("Terms").</p>

        <li>Age and Legal Capacity</li>
        <p>
          You affirm that you are at least 18 years of age and are considered a legal adult in your country of residence. By using Quarkle,
          you represent that you have the legal capacity to enter into a binding agreement.
        </p>

        <li>Nature of Service</li>
        <p>
          Quarkle offers open access to language model services. The content generated by Quarkle is autonomous, based on a broad spectrum
          of internet data, and does not necessarily reflect the views or ideologies of its creators.
        </p>

        <li>User Responsibilities</li>
        <p>
          You acknowledge the risks associated with using an open model at Quarkle, including exposure to potentially offensive, inaccurate,
          or inappropriate content. You agree to use Quarkle responsibly and not for any unlawful purposes. You are solely responsible for
          the way you use the service and any content you generate or interact with.
        </p>

        <li>Disclaimer of Warranties</li>
        <p>
          Quarkle is provided "as is" and with all faults, and hereby disclaims all warranties, whether express, implied, statutory, or
          otherwise.
        </p>

        <li>Limitation of Liability</li>
        <p>
          The creators of Quarkle shall not be liable for any indirect, incidental, special, consequential, or punitive damages, or any loss
          of profits or revenues, whether incurred directly or indirectly, or any loss of data, use, goodwill, or other intangible losses,
          resulting from (i) your access to or use of or inability to access or use Quarkle; (ii) any conduct or content of any third party
          on Quarkle; (iii) any content obtained from Quarkle; and (iv) unauthorized access, use, or alteration of your transmissions or
          content.
        </p>

        <li>Indemnification</li>
        <p>
          You agree to indemnify and hold harmless the creators of Quarkle and its officers, directors, employees, and agents from any and
          all claims, damages, losses, liabilities, and expenses (including attorneys' fees) arising from or related to your use of Quarkle.
        </p>

        <li>Modification of Terms</li>
        <p>
          The creators of Quarkle reserve the right to modify these terms at any time. You agree to review the terms regularly to ensure you
          are aware of any changes.
        </p>

        <li>Governing Law</li>
        <p>
          These Terms shall be governed by and construed in accordance with the laws of the United States without regard to its conflict of
          law principles.
        </p>

        <li>Acknowledgment</li>
        <p>By using Quarkle, you acknowledge that you have read, understood, and agree to be bound by these Terms of Service.</p>
      </ol>
    </>
  );
}
