export const theAdventureOfTheSpeckledBand = `
<span>“Very sorry to knock you up, Watson,” said he, “but it’s the common lot this morning. Mrs. Hudson has been knocked up, she retorted upon me, and I on you.”</span>
<span>“What is it, then—a fire?”</span>
<span>“No; a client. It seems that a young lady has arrived in a considerable state of excitement, who insists upon seeing me. She is waiting now in the sitting-room. Now, when young ladies wander about the metropolis at this hour of the morning, and knock sleepy people up out of their beds, I presume that it is something very pressing which they have to communicate. Should it prove to be an interesting case, you would, I am sure, wish to follow it from the outset. I thought, at any rate, that I should call you and give you the chance.”</span>
<p><b>“My dear fellow, I would not miss it for anything.”</b></p>
<span>I had no keener pleasure than in following Holmes in his professional investigations, and in admiring the rapid deductions, as swift as intuitions, and yet always founded on a logical basis with which he unravelled the problems which were submitted to him. I rapidly threw on my clothes and was ready in a few minutes to accompany my friend down to the sitting-room. A lady dressed in black and heavily veiled, who had been sitting in the window, rose as we entered.</span>
<span>“Good-morning, madam,” said Holmes cheerily. “My name is Sherlock Holmes. This is my intimate friend and associate, Dr. Watson, before whom you can speak as freely as before myself. Ha! I am glad to see that Mrs. Hudson has had the good sense to light the fire. Pray draw up to it, and I shall order you a cup of hot coffee, for I observe that you are shivering.”</span>
<span>“It is not cold which makes me shiver,” said the woman in a low voice, changing her seat as requested.</span>
<span>“What, then?”</span>
<span>“It is fear, Mr. Holmes. It is terror.” She raised her veil as she spoke, and we could see that she was indeed in a pitiable state of agitation, her face all drawn and grey, with restless frightened eyes, like those of some hunted animal. Her features and figure were those of a woman of thirty, but her hair was shot with premature grey, and her expression was weary and haggard. Sherlock Holmes ran her over with one of his quick, all-comprehensive glances.</span>
`;

export const test = `<p>"Papa, why the wait? I'm right here.<span class="my-comment" data-comment-id="comment1395">"</span></p><p><span class="my-comment" data-comment-id="comment1395">These words, carried by the Himalayan winds, enveloped me in cold whispers</span>.</p><p>"Tenzing, my dear boy, I live with so much regret from that day. Forgive me."</p><p>"There's nothing to forgive, Papa. It wasn't your fault. Just...<span class="my-comment" data-comment-id="comment1396"> it's quiet here without you</span>. Come, be with me again!"</p><p>Every dream inched Tenzing's voice closer, and tonight, his words sliced through the divide between sleep and wakefulness. Could this really be happening? Impossible.</p><p>I splashed some cold water on my face and headed out to gather the goats, their bleats filling the crisp morning air as we started our daily routine on the mountain slopes. "Tsewang, having those dreams again?" I saw Lhakpa in the corner, her silhouette half-draped in shadows, half-bathed in the nascent light of dawn.</p><p>"Yes, Lhakpa," I sighed, "the dreams, they don't relent.”</p><p>Lhakpa's eyes, always brimming with a quiet understanding, met mine. “Still climbing mountains in your sleep, Tsewang? Searching for him in cliffs and clouds?”</p><p>“I don’t have to search. He’s right there—older, wiser... he's everything I hoped he would be.”</p><p>A pause lingered between us, filled only by the whisper of the wind.</p><p>Lhakpa took a step closer, her presence a comforting warmth. “Perhaps it’s his way, or the mountain's way, of soothing your heart. These aren’t just dreams; they're the meetings of souls separated by fate, not by choice.”</p><p>“I just...” A lump formed in my throat as I turned away, staring over the jagged horizon.<span class="my-comment" data-comment-id="comment1397"> “I wish they were more than mere echoes of what could have been</span>.”</p><p>“Maybe they're not echoes, Tsewang. Maybe they’re promises,” she offered gently, placing a hand on my shoulder. “Promises of peace, someday, when you've both reached the mountain's true top.”</p><p>Beside us, unnoticed in our heavy exchange, sat my faithful companion, Sheru. His warm fur was matted with the snows of countless ascents and descents, always a silent witness to my unrest. Now, as if sensing the shift in the air between us, he nudged his muzzle into my hand. His dark eyes held a comfort that words often lack, a silent understanding that seemed to say, "Wherever your path leads, I walk with you." In that small gesture, I found an anchor, a reminder that some bonds, like the mountain beneath our feet, remain unshakeable.</p><p>In Lhakpa's words, I found no solutions, but a solace as enduring as the peaks that cradled us. And with that, we turned to greet the day's labors, the goats already stirring, oblivious to the weight of human hearts amid their rocky domains.</p><p></p>`;
